<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Diluluskan_mx-3 btn btn-sm d-flex align-i_490c98</name>
   <tag></tag>
   <elementGuidId>4f5fc21d-7fc4-4c07-ad2c-2e05a713e7ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='permohonan-table']/tbody/tr/td[5]/span/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.mx-3.btn.btn-sm.d-flex.align-items-center.btn-view-modal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d3732484-9440-4af0-921f-4ec7bad0e770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>d532f763-522a-4211-81e4-851de835ad8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mx-3 btn btn-sm d-flex align-items-center btn-view-modal</value>
      <webElementGuid>3c890770-2d37-43b0-9bdd-a1ec03078c42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-url</name>
      <type>Main</type>
      <value>https://mbsphr-dev.veecotech.com.my/integriti-tatatertib/political-involvement-notification/show/1</value>
      <webElementGuid>ed9befb4-8e59-4b64-9c0d-62ade07df1b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>747f3d89-caab-44f4-83d2-cff2fe345ab2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-original-title</name>
      <type>Main</type>
      <value>Lihat</value>
      <webElementGuid>fe85251d-c885-40df-b3e0-dcc955ef8ca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip971700</value>
      <webElementGuid>f6fd0a9a-7013-499f-b8be-f1205af9b7fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;permohonan-table&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[5]/span[@class=&quot;d-inline-flex align-items-center&quot;]/div[@class=&quot;action-btn bg-info ms-2&quot;]/a[@class=&quot;mx-3 btn btn-sm d-flex align-items-center btn-view-modal&quot;]</value>
      <webElementGuid>9035b482-76e8-4df9-969f-9862e8a3174c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='permohonan-table']/tbody/tr/td[5]/span/div/a</value>
      <webElementGuid>113d3bd2-aec4-4458-abec-ad8851fa940f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Diluluskan'])[1]/following::a[1]</value>
      <webElementGuid>918ffb8d-5197-412b-bd09-4d465e52eaa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DAP'])[1]/following::a[1]</value>
      <webElementGuid>fcdf9248-6955-45b1-b5bc-e5e9a5552deb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tunjuk 1 hingga 1 daripada 1 entri'])[1]/preceding::a[2]</value>
      <webElementGuid>eefa5e1c-fff2-4965-b3cc-9e2ffa2b2f90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sebelumnya'])[1]/preceding::a[2]</value>
      <webElementGuid>9e2ba001-42b7-4d36-9b38-ba991d2fcdf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[38]</value>
      <webElementGuid>30ef6048-a595-4a0c-b307-5e1bfbe81067</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/a</value>
      <webElementGuid>d1b993d5-b04b-46d2-9e13-04889b23f952</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#']</value>
      <webElementGuid>1b813b19-6162-4862-bffd-a00969bc1967</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
