<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Permohonan Saya_kelulusan-tab</name>
   <tag></tag>
   <elementGuidId>1562bc5c-73e3-4bce-837d-804ad4e5df30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='kelulusan-tab']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#kelulusan-tab</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1860c608-393d-42e0-be1c-a82f270226fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c23d5cd7-4e45-4438-8695-8618e0452525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>kelulusan-tab</value>
      <webElementGuid>3f105b7e-2eb6-4148-9bac-99a9c2fa6ff0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-100 btn btn-sub-button show-tab</value>
      <webElementGuid>807397d8-aa9a-4f87-b2ff-a1f6e5d4a680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Kelulusan
        </value>
      <webElementGuid>afe045e4-a8b7-4182-aa1a-cd00fbf36caf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kelulusan-tab&quot;)</value>
      <webElementGuid>e03b625b-aa4c-4d3f-9be2-2e9c3ea14135</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='kelulusan-tab']</value>
      <webElementGuid>bf9b7606-9024-4bdb-9413-d5d417c73f07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Permohonan Saya'])[1]/following::button[1]</value>
      <webElementGuid>8f267f22-541f-480c-8c5e-313320056639</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pemakluman Keahlian Dalam Parti Politik'])[3]/following::button[2]</value>
      <webElementGuid>da59a0f6-9c4a-4105-9b6a-7722750e8b33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Senarai Pemakluman Politik Saya'])[1]/preceding::button[1]</value>
      <webElementGuid>9d682099-66b4-4829-9d2b-6d42e22e39d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kelulusan']/parent::*</value>
      <webElementGuid>3c070459-62fa-49ed-b16d-c56797fda916</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button[2]</value>
      <webElementGuid>38c6b455-4d10-401c-86d0-c683f72f0c32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'kelulusan-tab' and (text() = '
            Kelulusan
        ' or . = '
            Kelulusan
        ')]</value>
      <webElementGuid>bf0475a7-8317-41bd-aa82-725d34ea68f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
