<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__party_name</name>
   <tag></tag>
   <elementGuidId>0f33c4fb-89a6-4372-b1d3-c9ea135169e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='party_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#party_name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>950ac178-a766-4591-ab46-0bcceae7aeb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4442a48e-f554-4c7a-87bc-1dd688162cda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control </value>
      <webElementGuid>ed0b6a9d-237c-4d3e-b794-cc5717536a09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>party_name</value>
      <webElementGuid>97b0803d-9745-4f63-a99b-064e10c8bfff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>party_name</value>
      <webElementGuid>2e1de1a7-78f6-4e58-84b3-577a3824ba2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-asterisk-done</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b13f2933-6198-4b13-bfb2-a2f89ed1726a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nama Parti Politik</value>
      <webElementGuid>73d47871-47ca-401c-8de3-9e9f576d5f1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Sila lengkapkan Nama Parti Politik</value>
      <webElementGuid>d2906162-7f15-44da-b498-9f4c9cd5eaf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;party_name&quot;)</value>
      <webElementGuid>c0410038-ed33-42e5-be0c-54adcef87b09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='party_name']</value>
      <webElementGuid>484ff106-b9bd-417c-ad8b-70bfbeaf10f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='politicalInvolvementForm']/div[2]/div[2]/div/input</value>
      <webElementGuid>332e7788-c4e5-4a80-8124-46141b878bdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/input</value>
      <webElementGuid>0e03b92d-4dba-43e6-9efd-a024a0984ffe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'party_name' and @name = 'party_name' and @placeholder = 'Nama Parti Politik' and @title = 'Sila lengkapkan Nama Parti Politik']</value>
      <webElementGuid>ebbdec10-60e0-45a1-ae05-289721e9838d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
