<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Perakuan_employee_declaration</name>
   <tag></tag>
   <elementGuidId>ed39f1fd-c055-4b15-91a9-8ed817b3208b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='employee_declaration']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#employee_declaration</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0700a234-1c3f-4c73-85a9-79ff192ab765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input </value>
      <webElementGuid>08d71b49-15e8-40b5-a240-e51b9db41156</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>96ae91fe-a7b9-45ae-9f6d-924a0d47a2e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>de5fff36-7e66-4233-b238-d03ec668f57f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>employee_declaration</value>
      <webElementGuid>35eb9c2d-89b9-4991-9ef6-68eff6964cb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>employee_declaration</value>
      <webElementGuid>10806862-f391-4c01-aa11-079040d2ff14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-asterisk-done</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4dcaa3ce-a285-479b-a118-b365666e7cb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pengakuan Pegawai</value>
      <webElementGuid>f350b59e-92de-4be2-b8ac-9066395cdcda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Sila lengkapkan Pengakuan Pegawai</value>
      <webElementGuid>d5a16655-bf48-486d-8ba5-f42700ba8b3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;employee_declaration&quot;)</value>
      <webElementGuid>3ef4e66e-ce4b-4b7a-b2df-2ca10f0af996</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='employee_declaration']</value>
      <webElementGuid>9941aa6f-cc5b-41d1-9129-7a7d57ce0cfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='politicalInvolvementForm']/div[4]/div[3]/div/input</value>
      <webElementGuid>cd90e9fd-867c-4a22-aa29-9ef6f55c5fb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/div/input</value>
      <webElementGuid>a2bb702e-77be-4fc8-8bcc-7a4aeaa78802</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'employee_declaration' and @name = 'employee_declaration' and @placeholder = 'Pengakuan Pegawai' and @title = 'Sila lengkapkan Pengakuan Pegawai']</value>
      <webElementGuid>31dc1128-0f49-484b-a67c-0e2bfce8f6f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
