<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Catatan  Komen_remarks</name>
   <tag></tag>
   <elementGuidId>7ff71526-a90e-425a-a3ba-792f861d76cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='remarks']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#remarks</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>5d1a530c-56eb-4b95-bf3d-dc1062dfa9f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f968aae5-16e1-4eff-a4d6-dc304ca3a904</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>remarks</value>
      <webElementGuid>0868d1a1-e6af-482b-9c62-2902e421eb03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>remarks</value>
      <webElementGuid>430621fb-c5b4-4318-96da-8974398fea59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>9f0cfaff-5ae1-4bbe-ae20-4245b4f1966a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan catatan atau komen...</value>
      <webElementGuid>331fe79c-995a-4ea1-9101-806474d51c35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Sila lengkapkan Catatan / Komen</value>
      <webElementGuid>7ffcf055-a778-41fe-ad90-e6ebe224a7c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>7278c625-d9d5-42d2-836a-f727c3b14267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;remarks&quot;)</value>
      <webElementGuid>2addde1d-e80c-4e5f-a3a3-806542fac3c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='remarks']</value>
      <webElementGuid>92bf9de7-2b73-44dc-8fa2-f24e6168ace1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='approvalForm']/div/div[2]/div/textarea</value>
      <webElementGuid>6705f0af-d5e7-4181-8b86-41dfb082054e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>5fc29cff-1e9c-4d7c-a7bd-5de77818069a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'remarks' and @name = 'remarks' and @placeholder = 'Masukkan catatan atau komen...' and @title = 'Sila lengkapkan Catatan / Komen']</value>
      <webElementGuid>8458ea5f-08b9-41fb-82a6-379a093086fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
