<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Perakuan_acknowledge</name>
   <tag></tag>
   <elementGuidId>23f44bd7-a03a-4c90-b704-0ed7d1d42097</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='acknowledge']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#acknowledge</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>34e08a69-1656-4c3d-8f8c-bb3a8ce9627b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>7e929d74-013f-4a66-bcb9-36ca4f8015f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>8ea08925-5002-4552-883d-68149b6e6fd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>acknowledge</value>
      <webElementGuid>d35ee89e-6aeb-4112-b760-44c96d71e3d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>acknowledge</value>
      <webElementGuid>ce2363b9-8b98-4444-9fba-c697d0af8236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>63538535-72f2-4f68-9483-530353ab2d42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-asterisk-done</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7632a594-740a-4250-ba3f-6697fc48003d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Saya mengaku bahawa segala maklumat yang diberikan adalah benar dan tepat.</value>
      <webElementGuid>2542976a-d727-4868-9852-3b92918ace56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Sila lengkapkan Saya mengaku bahawa segala maklumat yang diberikan adalah benar dan tepat.</value>
      <webElementGuid>34f46ad8-46df-42b1-a597-f59b0108dff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;acknowledge&quot;)</value>
      <webElementGuid>b804c5aa-8d2b-4435-b7d8-7a0f8deb9fff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='acknowledge']</value>
      <webElementGuid>a0192dd1-c689-4b82-838f-67f3eba2c8c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='mainForm']/div[5]/div/div[2]/div/div/input</value>
      <webElementGuid>d7ef9629-02e1-4650-ba9e-d7804a59b1cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/div/div/input</value>
      <webElementGuid>62f26d37-e764-4e6b-95a2-11134db03acc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'acknowledge' and @id = 'acknowledge' and @placeholder = 'Saya mengaku bahawa segala maklumat yang diberikan adalah benar dan tepat.' and @title = 'Sila lengkapkan Saya mengaku bahawa segala maklumat yang diberikan adalah benar dan tepat.']</value>
      <webElementGuid>34c1351e-0201-4880-9014-bdcfb4d72cbe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
