<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__party_name</name>
   <tag></tag>
   <elementGuidId>3356338c-4bb6-4989-a6d5-cc7ae18adc1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='party_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;party_name&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e02101d7-9aa1-44da-9a69-c02185aa7903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2206a678-51cb-481f-aed2-86842c1d21a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>party_name</value>
      <webElementGuid>ee70c7e6-b197-47cf-8e3d-6a9485addacd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>7054dca7-de50-47b6-acc6-a4a06af8a42a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-asterisk-done</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>787861f5-3d3f-4379-99ae-4852f8848d0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Sila lengkapkan </value>
      <webElementGuid>20d41efe-4c7f-4916-b3ee-19172ec7063f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainForm&quot;)/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 mb-3&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>294335a4-e1cd-4c63-a390-c6f2685282ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='party_name']</value>
      <webElementGuid>98b78005-17e9-4344-9596-6126a673989e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='mainForm']/div[3]/div/div[2]/div/div/input</value>
      <webElementGuid>c97b3834-96ac-459e-a1d9-ab0e78bcd3a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div/input</value>
      <webElementGuid>7fc3cbe5-c27a-4bc6-a87b-2533f51a6d7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'party_name' and @title = 'Sila lengkapkan ']</value>
      <webElementGuid>aa6fd342-5360-4fb9-a151-ee35e1bbdfcd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
