<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__btn btn-sm btn-icon d-flex align-items-c_163dfb</name>
   <tag></tag>
   <elementGuidId>31008592-446b-4f8c-b64f-1ebc4945f3c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='permohonan-table']/tbody/tr/td[7]/span/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-sm.btn-icon.d-flex.align-items-center.justify-content-center</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9ab68e18-eeb6-44a8-9845-b8d4fa3e7e13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://mbsphr-dev.veecotech.com.my/integriti-tatatertib/political-involvement/4/edit</value>
      <webElementGuid>79585dc7-0633-4bde-a543-73b8e0604c7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-icon d-flex align-items-center justify-content-center</value>
      <webElementGuid>cd952f12-f43c-424d-9031-2f87c13566f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dusk</name>
      <type>Main</type>
      <value>btn-edit</value>
      <webElementGuid>4037d8df-313f-4958-94b5-9c5ca39838df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>f687a8f2-32c6-42ec-9d0a-029cc6c41916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-original-title</name>
      <type>Main</type>
      <value>Kemaskini</value>
      <webElementGuid>8d92f5be-cf61-482b-b753-46f2ab57e246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip547983</value>
      <webElementGuid>fe06d8ed-7c6e-49f6-b9be-5805cf67f937</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;permohonan-table&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[7]/span[@class=&quot;d-inline-flex align-items-center gap-2&quot;]/div[@class=&quot;action-btn bg-warning&quot;]/a[@class=&quot;btn btn-sm btn-icon d-flex align-items-center justify-content-center&quot;]</value>
      <webElementGuid>9d60e207-5727-48ff-a6f9-cc49f566c093</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='permohonan-table']/tbody/tr/td[7]/span/div[2]/a</value>
      <webElementGuid>429d95a6-28fc-4163-b85d-be3f775e3054</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='—'])[1]/following::a[2]</value>
      <webElementGuid>67a8a8f8-5ede-446d-95df-af9bee3d3aeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dalam Semakan'])[1]/following::a[2]</value>
      <webElementGuid>0c249984-9c51-45f9-adca-f280ded93231</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tunjuk 1 hingga 1 daripada 1 entri'])[1]/preceding::a[1]</value>
      <webElementGuid>2208e7e9-3b48-4b84-b7c9-2364ab262fc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sebelumnya'])[1]/preceding::a[1]</value>
      <webElementGuid>e431243f-6aa4-4f07-b659-2c63be8a5db7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://mbsphr-dev.veecotech.com.my/integriti-tatatertib/political-involvement/4/edit')]</value>
      <webElementGuid>e3f3f7e6-72f4-43e2-9b33-faa84646db91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div[2]/a</value>
      <webElementGuid>03b1be9e-544b-4079-848d-71b9b1861b25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://mbsphr-dev.veecotech.com.my/integriti-tatatertib/political-involvement/4/edit']</value>
      <webElementGuid>6266f244-4a7b-4cd1-98cc-7b8af70c2c04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
