<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Permohonan Saya_kelulusan-tab</name>
   <tag></tag>
   <elementGuidId>cc339473-6507-4f9e-85b6-f7ed3e97e692</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='kelulusan-tab']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#kelulusan-tab</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fe067ed8-4071-420c-b30c-6e855f11ecd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>093b3f91-bd5d-4879-b78d-20db162d00cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>kelulusan-tab</value>
      <webElementGuid>da6d29b4-f676-4d23-b4b3-7f434141bc75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-100 btn btn-sub-button show-tab</value>
      <webElementGuid>77915bb4-f803-4e00-9528-bf6eb00beb18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Kelulusan
        </value>
      <webElementGuid>ea0e623f-0ad9-4611-af5e-167a02ce2036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kelulusan-tab&quot;)</value>
      <webElementGuid>8b101e7f-d78d-487f-92c6-7c613b592571</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='kelulusan-tab']</value>
      <webElementGuid>4d3bf2f6-2cdd-42ac-a681-b367fae335c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Permohonan Saya'])[1]/following::button[1]</value>
      <webElementGuid>8b3d7714-991d-4397-8716-323ae2a9c8ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Peringatan:'])[1]/following::button[2]</value>
      <webElementGuid>8f4f4ad3-1a7b-4452-bb0c-5144b7f9d5c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Permohonan Saya'])[2]/preceding::button[1]</value>
      <webElementGuid>0d13705d-03dc-4581-98d4-e7a5d7bfc012</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kelulusan']/parent::*</value>
      <webElementGuid>e469ee1e-ca5a-4de3-b7d3-539d56a45b6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button[2]</value>
      <webElementGuid>34f5a9e2-f689-461c-a474-81f594f89b42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'kelulusan-tab' and (text() = '
            Kelulusan
        ' or . = '
            Kelulusan
        ')]</value>
      <webElementGuid>716c6c09-a35a-45d7-a659-95414b6a48a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pemakluman Penglibatan Politik'])[2]/following::button[2]</value>
      <webElementGuid>d8977635-f608-4e12-95de-b866d9d41e8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button[2]</value>
      <webElementGuid>9b49dbbe-efca-4c9e-bf31-e4d371c28845</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
