<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Batal_confirmSubmit</name>
   <tag></tag>
   <elementGuidId>7b30dcb7-3d33-463d-a48b-6aa940f980cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='confirmSubmit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#confirmSubmit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>55105395-1d56-4ecc-8618-0e69de8bc101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2aaeecca-fb29-44c1-b34c-bd478308f2cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirmSubmit</value>
      <webElementGuid>b11e1c58-bdc4-461f-b41e-a523531491ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>90cf88ef-c5d7-42cf-8f4c-e4ad8318a13a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kemaskini</value>
      <webElementGuid>3908c8ae-1b78-4612-bc2f-458e0ca27c08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;confirmSubmit&quot;)</value>
      <webElementGuid>45155415-ef97-4abf-a295-2b4f9e8f1ac6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='confirmSubmit']</value>
      <webElementGuid>a7193fab-6804-49dd-828e-410d787bb871</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='confirmModal']/div/div/div[3]/button[2]</value>
      <webElementGuid>489b1133-e25a-487c-953f-a8b48c019418</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[1]/following::button[1]</value>
      <webElementGuid>7ba31802-6107-4181-8427-b12dec3ec662</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sahkan untuk mengemaskini permohonan ini? Pastikan semua maklumat adalah tepat.'])[1]/following::button[2]</value>
      <webElementGuid>0de4a5b5-da6b-4f6f-8b62-10314373c495</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kemaskini']/parent::*</value>
      <webElementGuid>d9a85552-7815-4142-8bd4-9ee4adffcc8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[3]/button[2]</value>
      <webElementGuid>b617cbd0-251f-468e-914f-86739c5601bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'confirmSubmit' and (text() = 'Kemaskini' or . = 'Kemaskini')]</value>
      <webElementGuid>ec6062ba-9226-4222-95dd-6dcf21282aef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
