<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Bahagian II Jenis Permohonan_type1</name>
   <tag></tag>
   <elementGuidId>aaf90c29-2467-40f9-9d97-1f1860be9afb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='type1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#type1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a597953f-fbac-4c9c-967c-7fd4ba217383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>e606ec64-bc4b-477b-b5b5-2e677045a10a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>83978796-5572-404c-9bea-60ebd50ccf2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>application_type</value>
      <webElementGuid>59296098-f822-4232-8ab1-89bc287eaa6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>type1</value>
      <webElementGuid>5bf735f5-f8c0-4117-93f1-e150142c6ab7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>hold_party_office</value>
      <webElementGuid>9b50ce4b-d118-4b48-a56b-b0abc9b517d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-asterisk-done</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>61d26167-88b6-4201-9e4c-a4c0d9fea8ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Memegang jawatan dalam parti politik (Kumpulan Sokongan)</value>
      <webElementGuid>d32761b6-ad97-4c0b-861b-77a8ce11b100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Sila lengkapkan Memegang jawatan dalam parti politik (Kumpulan Sokongan)</value>
      <webElementGuid>f293f45d-f81a-4412-82d9-59f1899db0ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;type1&quot;)</value>
      <webElementGuid>8d95d2b7-0477-46e0-be63-7261d6b1b838</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='type1']</value>
      <webElementGuid>78ac9d60-d673-447a-8442-616e175c2b2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='politicalForm']/div[2]/div/div[2]/div/input</value>
      <webElementGuid>72de8a32-c7a7-4998-9bbf-d2a88dbf8254</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>365877a2-342b-434b-b214-75164c755f34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'application_type' and @id = 'type1' and @placeholder = 'Memegang jawatan dalam parti politik (Kumpulan Sokongan)' and @title = 'Sila lengkapkan Memegang jawatan dalam parti politik (Kumpulan Sokongan)']</value>
      <webElementGuid>177f35fd-d2b7-42cd-96b3-6d69d5636208</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
