<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Perakuan_acknowledge</name>
   <tag></tag>
   <elementGuidId>503acc3c-caa5-4241-b8ef-1b6770e78f07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='acknowledge']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#acknowledge</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0f933f65-8596-4ec0-9ed4-3954189c2875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>1fba2a3a-a776-4d4f-8f15-d14e9b20349d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>3a8d51a8-75fb-4549-b886-36fb95714448</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>acknowledge</value>
      <webElementGuid>7d5d7e53-e4c3-4142-95d4-01a90a4cdb62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>acknowledge</value>
      <webElementGuid>008682cf-a881-4a9e-a5d4-33ed6aa2293e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>4ab35098-9119-4084-8360-a99cb35190a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-asterisk-done</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8de869a0-bc4d-4af4-b217-267918106319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Saya mengaku bahawa segala maklumat yang diberikan adalah benar dan tepat.</value>
      <webElementGuid>7f3c47de-a2bd-4098-b78f-31ba822584dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Sila lengkapkan Saya mengaku bahawa segala maklumat yang diberikan adalah benar dan tepat.</value>
      <webElementGuid>6bf52b8d-4f41-4606-861c-0b535a419e85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;acknowledge&quot;)</value>
      <webElementGuid>e6cfe573-d5f6-4bcd-9925-a58d7d77d153</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='acknowledge']</value>
      <webElementGuid>4e8bb903-60bf-41d0-9b33-4dfd7e13deed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='mainForm']/div[5]/div/div[2]/div/div/input</value>
      <webElementGuid>b647efa4-b9b7-437c-ad69-d18ac2d6905d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/div/div/input</value>
      <webElementGuid>17792275-9bf4-4faa-a0d0-34f5b7c7b37e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'acknowledge' and @id = 'acknowledge' and @placeholder = 'Saya mengaku bahawa segala maklumat yang diberikan adalah benar dan tepat.' and @title = 'Sila lengkapkan Saya mengaku bahawa segala maklumat yang diberikan adalah benar dan tepat.']</value>
      <webElementGuid>9a27f55d-f3f6-4356-9715-a4c21b484a06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
