<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Perakuan_acknowledge</name>
   <tag></tag>
   <elementGuidId>68adbf06-841f-4510-8d06-fa8b078b0a10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='acknowledge']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#acknowledge</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>af7766d4-fcc2-4cd9-a66d-8602869845cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>20fb4d06-5e51-4787-9bf1-0eb7a70eabee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>85f663cd-c311-4bd6-8072-cd6674e3532a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>acknowledge</value>
      <webElementGuid>99d92606-c48e-4b21-8af0-514d01b79ea0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>acknowledge</value>
      <webElementGuid>3a759e61-7494-4fb7-84ce-bad99f97ce86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b9427923-4030-4f3a-8436-4bb3f7be4bc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-asterisk-done</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2cb34e12-dd1f-47d9-aedd-01a624d22efc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Saya mengaku bahawa segala maklumat yang diberikan adalah benar dan tepat.</value>
      <webElementGuid>8e693df4-acc7-452c-853b-e8aa6341f385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Sila lengkapkan Saya mengaku bahawa segala maklumat yang diberikan adalah benar dan tepat.</value>
      <webElementGuid>785fe15b-8187-4d95-9155-28a0e94b05ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;acknowledge&quot;)</value>
      <webElementGuid>c272ff89-7f21-4c93-9af1-f4c3f2639111</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='acknowledge']</value>
      <webElementGuid>325513d1-7871-42a4-9391-aa9de53ef8e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='mainForm']/div[5]/div/div[2]/div/div/input</value>
      <webElementGuid>5ab1fcbf-efb4-4de9-a374-1984640dd842</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/div/div/input</value>
      <webElementGuid>3bee3654-891b-48de-81c4-06afe1201757</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'acknowledge' and @id = 'acknowledge' and @placeholder = 'Saya mengaku bahawa segala maklumat yang diberikan adalah benar dan tepat.' and @title = 'Sila lengkapkan Saya mengaku bahawa segala maklumat yang diberikan adalah benar dan tepat.']</value>
      <webElementGuid>aeb1dfa5-750a-4ff0-b580-077366af8858</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
