<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Perakuan_acknowledge</name>
   <tag></tag>
   <elementGuidId>de701340-9897-482f-86d5-377966badf6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='acknowledge']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#acknowledge</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9a56b812-7261-48a7-9e6e-e7d72ee1c630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>85f33b39-6409-433c-8fd4-e16f9a44daba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f9e847ff-6737-4b5e-a3c3-374799ab5e7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>acknowledge</value>
      <webElementGuid>12bc506a-f10f-46ed-95fb-5716c5507d3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>acknowledge</value>
      <webElementGuid>d1ee7878-9938-45a7-aa49-fe5bf87c732a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>25bf7b80-7efe-43e1-80ca-6aed7f76b860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-asterisk-done</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>82680dd2-1fb4-433b-ac14-8619e165e273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Saya mengaku bahawa segala maklumat yang diberikan adalah benar dan tepat.</value>
      <webElementGuid>c7f3c5bc-602c-4f88-9d69-bdbbee3539bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Sila lengkapkan Saya mengaku bahawa segala maklumat yang diberikan adalah benar dan tepat.</value>
      <webElementGuid>35de345d-382d-486c-806b-2c6301d933ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;acknowledge&quot;)</value>
      <webElementGuid>807702dd-7534-4c78-8766-67a1c6356a31</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='acknowledge']</value>
      <webElementGuid>23c7c214-35f7-46ab-8ad2-dbe2aa2b78dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='mainForm']/div[5]/div/div[2]/div/div/input</value>
      <webElementGuid>9eef3bba-e952-47f4-a43d-e4f0295c4074</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/div/div/input</value>
      <webElementGuid>23016f89-2a88-42c2-926e-53a7883934a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'acknowledge' and @id = 'acknowledge' and @placeholder = 'Saya mengaku bahawa segala maklumat yang diberikan adalah benar dan tepat.' and @title = 'Sila lengkapkan Saya mengaku bahawa segala maklumat yang diberikan adalah benar dan tepat.']</value>
      <webElementGuid>e3a24868-2ecd-4251-8475-5941e50c8c77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
