<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button__btn btn-sm btn-icon bs-pass-para d-_6d769a</name>
   <tag></tag>
   <elementGuidId>5341f694-c51a-44d4-8fa3-8660e6c87247</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-sm.btn-icon.bs-pass-para.d-flex.align-items-center.justify-content-center.delete</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>54aad38f-1286-4c8d-867a-90da4415bb95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>b932e5c2-5985-43ae-81b3-591096780ce0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-icon bs-pass-para d-flex align-items-center justify-content-center delete</value>
      <webElementGuid>d59d8b36-ce4a-4b57-ae6b-083041d76d32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dusk</name>
      <type>Main</type>
      <value>btn-delete-17</value>
      <webElementGuid>099fc22c-6439-48ea-aeab-c6c3b18bf2d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>5f6954cc-0dd1-4289-b271-29fb9a908130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-original-title</name>
      <type>Main</type>
      <value>Padam</value>
      <webElementGuid>1296d1f3-4461-40a6-8705-967eb4dc0b44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip512351</value>
      <webElementGuid>2ec27089-a718-4cb4-a70e-55aa9f296ed3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;permohonan-table&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[7]/span[@class=&quot;d-inline-flex align-items-center gap-2&quot;]/div[@class=&quot;action-btn bg-danger&quot;]/form[1]/button[@class=&quot;btn btn-sm btn-icon bs-pass-para d-flex align-items-center justify-content-center delete&quot;]</value>
      <webElementGuid>fc758174-1355-4a2d-aa32-5816f72266b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[2]</value>
      <webElementGuid>9a0874e6-e722-46c2-8d6c-50e827e4f002</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='permohonan-table']/tbody/tr/td[7]/span/div[3]/form/button</value>
      <webElementGuid>f59c52e9-693e-4d1a-ac1d-befe4da839ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='—'])[1]/following::button[1]</value>
      <webElementGuid>fbdcf4ac-2700-439e-9bd0-2fc618c8daef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dalam Semakan'])[1]/following::button[1]</value>
      <webElementGuid>1ce3fb0d-7090-47cb-9a8f-a342b0178880</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Memegang jawatan parti (Kumpulan Sokongan)'])[2]/preceding::button[1]</value>
      <webElementGuid>d5270cc1-d720-4266-83c3-b117b07e7654</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DAP'])[1]/preceding::button[1]</value>
      <webElementGuid>a1f86e63-f4f4-475f-b195-edb43583dfec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button</value>
      <webElementGuid>0124e6a4-aaff-4241-a0f0-1d0cc38703f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit']</value>
      <webElementGuid>d7cc6ab7-fd47-4c66-af3d-f3d367054836</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
