<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Permohonan Saya_kelulusan-tab</name>
   <tag></tag>
   <elementGuidId>a5331d32-7195-43e4-8ca0-d3ed49085e74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='kelulusan-tab']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#kelulusan-tab</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5f5f4e9b-bf3a-4526-9829-619667aca1b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d6212490-16be-4c9f-8ee7-a31ca1a13ec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>kelulusan-tab</value>
      <webElementGuid>187e7d73-7ada-408c-a5ba-b6f2ea9f5619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-100 btn btn-sub-button show-tab</value>
      <webElementGuid>fe81d43f-52c3-47c6-b12e-bd36dae0a883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Kelulusan
        </value>
      <webElementGuid>7b45df34-19b6-4678-83e1-6e80065c1c42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kelulusan-tab&quot;)</value>
      <webElementGuid>28b0d665-d8f4-439c-a453-fac3b5fc6ce6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='kelulusan-tab']</value>
      <webElementGuid>649d967c-55da-4b57-a4e9-5d001550a125</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Permohonan Saya'])[1]/following::button[1]</value>
      <webElementGuid>066071b3-b8e3-496d-8edd-d99c9d8b670b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Peringatan:'])[1]/following::button[2]</value>
      <webElementGuid>b4e6e6ca-4cde-4bcc-86a9-51c0d70f8a6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Permohonan Saya'])[2]/preceding::button[1]</value>
      <webElementGuid>0ecfa14a-68fc-4bde-ae60-77a338d68667</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kelulusan']/parent::*</value>
      <webElementGuid>1177c06b-938a-4a59-97cb-8a5afd90f092</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button[2]</value>
      <webElementGuid>050d05e0-1956-4be6-b1e6-3253cc136cd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'kelulusan-tab' and (text() = '
            Kelulusan
        ' or . = '
            Kelulusan
        ')]</value>
      <webElementGuid>69516bb6-a85c-487c-b3f4-64f4fa08e27e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
