<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Permohonan Saya_kelulusan-tab</name>
   <tag></tag>
   <elementGuidId>7384b554-bf91-48a7-bdee-20d4a9c7dd49</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='kelulusan-tab']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#kelulusan-tab</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f3246bcd-ca1d-4207-9e07-9c3523b95c71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f8010e80-b796-45cd-8929-86caa59989e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>kelulusan-tab</value>
      <webElementGuid>109a67e4-af2a-4151-b23b-5aab6a67d519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-100 btn btn-sub-button show-tab</value>
      <webElementGuid>e6a56e0c-5092-41e5-bd74-f4ce1b4ab101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Kelulusan
        </value>
      <webElementGuid>19aba125-8e44-4790-ac69-727c53104172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kelulusan-tab&quot;)</value>
      <webElementGuid>dc55510e-ca1e-4f61-be2a-ee831c3c21bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='kelulusan-tab']</value>
      <webElementGuid>a689e77a-82cb-4344-8276-f7c6c3504224</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Permohonan Saya'])[1]/following::button[1]</value>
      <webElementGuid>a20dcd12-9390-4f9b-9dc3-6a8dea619ce5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Peringatan:'])[1]/following::button[2]</value>
      <webElementGuid>82ca4db1-db7b-4d9b-a4eb-cb81f2bb4a0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Permohonan Saya'])[2]/preceding::button[1]</value>
      <webElementGuid>61aefbfe-38b5-44b3-afe0-bdeadcc405ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kelulusan']/parent::*</value>
      <webElementGuid>0258f430-f4f0-4cf2-bffd-8ecc4dd77ed5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button[2]</value>
      <webElementGuid>0ec59afd-02f8-4767-a18b-91c305be8284</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'kelulusan-tab' and (text() = '
            Kelulusan
        ' or . = '
            Kelulusan
        ')]</value>
      <webElementGuid>cec33ce4-01f8-41ce-91e5-8a13ef7c7cf7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
