<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Pemberitahuan Penting_acknowledgement</name>
   <tag></tag>
   <elementGuidId>921bc763-9216-4924-9902-63ee29949619</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='acknowledgement']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#acknowledgement</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aef7726f-9429-4fe1-807b-1baaa61ea974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>8060d64c-82d0-49df-984d-8da1a4e363c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>19b48dfc-d9d3-4f02-ad9a-30be7e52b098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>6bdde2da-6050-4423-88ae-2d434a4b2667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>acknowledgement</value>
      <webElementGuid>08877ce7-2fff-4b5e-b24d-6deae40e5f5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>acknowledgement</value>
      <webElementGuid>419a3975-d5fc-4b93-a927-8523dfd8b178</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-asterisk-done</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6cf7e4d1-d564-44e6-be99-f24ca64088eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pengakuan Pemohon</value>
      <webElementGuid>4a55ff67-1186-4f5c-9708-f604beb84ef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Sila lengkapkan Pengakuan Pemohon</value>
      <webElementGuid>b44af36c-98ba-4fdb-bd09-ee2744db7731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;acknowledgement&quot;)</value>
      <webElementGuid>da176bfd-392d-4b2c-8cc5-81354989bfba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='acknowledgement']</value>
      <webElementGuid>2eb6085f-e24c-4cc4-85e0-ba4174a48508</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='acknowledgementForm']/div/div/input</value>
      <webElementGuid>ca448d17-c781-45ed-b13e-a8a4f9904fe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/input</value>
      <webElementGuid>f1b43f98-5761-4c4f-8447-4d42c79ce04f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'acknowledgement' and @name = 'acknowledgement' and @placeholder = 'Pengakuan Pemohon' and @title = 'Sila lengkapkan Pengakuan Pemohon']</value>
      <webElementGuid>e98ef620-d02c-40a8-861c-47abfd3fba48</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
