<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__party_name</name>
   <tag></tag>
   <elementGuidId>45636851-be3a-4048-8198-228af7e582b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='party_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;party_name&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>147361eb-5c6e-4cc8-9125-5567c57bb306</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>08e0f5b6-4542-4124-8c63-191d05110c33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>party_name</value>
      <webElementGuid>e1b0e6ef-5dc0-46fb-945d-d09b9af84fe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>412e1a68-359e-4a7f-a7fc-0b42f770d916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-asterisk-done</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9e5a5bd5-77ed-45b8-847e-7f38c404fccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Sila lengkapkan </value>
      <webElementGuid>b0ac3bff-e2af-4f43-ae06-8070c0b81fc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainForm&quot;)/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 mb-3&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>6418fa39-4528-48ec-aa11-271054eb3319</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='party_name']</value>
      <webElementGuid>6b98c4ef-759e-4c0b-8812-dc5680ac4eb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='mainForm']/div[3]/div/div[2]/div/div/input</value>
      <webElementGuid>dde87d6f-55bf-4d32-9219-cdea65cfb02f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div/input</value>
      <webElementGuid>41a72b77-635e-4938-8aa0-90432d2899dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'party_name' and @title = 'Sila lengkapkan ']</value>
      <webElementGuid>dbe6ddc0-fd7a-42f4-9515-f5cc7f3bb5bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
