<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Perakuan_acknowledge</name>
   <tag></tag>
   <elementGuidId>38f3a642-950b-44e0-b040-b0da25aa6e2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='acknowledge']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#acknowledge</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>48ce4e39-f072-4db9-9899-3927ea51f78d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>1b176f94-9362-4a0a-b205-c8a7b20ed9c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>5a36c954-beb0-4f18-b027-9c87e4c7b4cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>acknowledge</value>
      <webElementGuid>45d2ee60-3ce7-45cb-b106-841d63fb196e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>acknowledge</value>
      <webElementGuid>efb4e272-61e4-4798-a432-043a9bff3937</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ff38223f-44d8-4514-9650-51377f29378b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-asterisk-done</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d45939ac-a200-4327-af0d-4d2d3b7252b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Saya mengaku bahawa segala maklumat yang diberikan adalah benar dan tepat.</value>
      <webElementGuid>e5db3b71-3419-4156-ac98-7cf1461764fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Sila lengkapkan Saya mengaku bahawa segala maklumat yang diberikan adalah benar dan tepat.</value>
      <webElementGuid>588bf999-061f-4cc0-afc5-acf0e66ba98c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;acknowledge&quot;)</value>
      <webElementGuid>0e818383-0e79-485b-9aa5-e220d631c45c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='acknowledge']</value>
      <webElementGuid>87596115-9838-4468-9775-b3833d6723e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='mainForm']/div[5]/div/div[2]/div/div/input</value>
      <webElementGuid>3d63e147-a25c-4028-8ab8-e467889d58af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/div/div/input</value>
      <webElementGuid>8affa3d4-ac54-4266-8356-df70969e3049</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'acknowledge' and @id = 'acknowledge' and @placeholder = 'Saya mengaku bahawa segala maklumat yang diberikan adalah benar dan tepat.' and @title = 'Sila lengkapkan Saya mengaku bahawa segala maklumat yang diberikan adalah benar dan tepat.']</value>
      <webElementGuid>58b9ff42-b469-4d16-a98b-736613a79397</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
