<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Jawatan Yang Akan Dipegang (jika_dda1b9</name>
   <tag></tag>
   <elementGuidId>38e03fa9-43ca-4648-9f2c-fa0306c6018a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='party_position']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;party_position&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fab0747a-ff33-4edb-8b73-e6578987c608</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>party_position</value>
      <webElementGuid>229e2f4a-3dc3-4c80-a810-087f6ff893cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>20496786-9059-4841-a8be-10a1739548e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Sila lengkapkan </value>
      <webElementGuid>7af5a3c1-e993-4944-a660-4c48dbf6d3a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;politicalForm&quot;)/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;row g-2&quot;]/div[@class=&quot;col-md-12&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>cd22f864-0be6-4aed-b751-c2fd10944ab3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='party_position']</value>
      <webElementGuid>7cd2f1a5-3948-4026-b2e6-c987004e84b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='politicalForm']/div[3]/div/div[2]/div/div[3]/input</value>
      <webElementGuid>48a64c75-ebfd-4f92-b711-65773f2dc8f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/input</value>
      <webElementGuid>ad343d3a-d87b-4f84-8088-0f117287f5c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'party_position' and @title = 'Sila lengkapkan ']</value>
      <webElementGuid>81ef22a5-7870-42cd-9dc4-1fb788e2a50e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
