<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Ditolak_mx-3 btn btn-sm d-flex align-item_2096f1</name>
   <tag></tag>
   <elementGuidId>f402866e-85eb-4d13-9b4c-1f7356b5580f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='kelulusan-table']/tbody/tr/td[8]/span/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.mx-3.btn.btn-sm.d-flex.align-items-center.btn-view-modal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fd5bc9b4-577d-4e9e-9438-148d93a481cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>c24da736-1472-4e5c-914f-cdafcf86d6c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mx-3 btn btn-sm d-flex align-items-center btn-view-modal</value>
      <webElementGuid>9bf0c041-5a35-4484-8114-49a032a1020e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-url</name>
      <type>Main</type>
      <value>https://mbsphr-dev.veecotech.com.my/integriti-tatatertib/political-involvement-admin/10</value>
      <webElementGuid>a7a85bfe-3fe7-44ca-8d3b-d0d50ce593a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>4184121b-0ed7-4fc1-80e7-d71ef3512c83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-original-title</name>
      <type>Main</type>
      <value>Lihat</value>
      <webElementGuid>659754ed-77e1-46ab-84d8-0daf5f4fa24e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip780735</value>
      <webElementGuid>9ea3ce07-8dd1-481a-9ae9-fccd60c3913d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kelulusan-table&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[8]/span[@class=&quot;d-inline-flex align-items-center&quot;]/div[@class=&quot;action-btn bg-info ms-2&quot;]/a[@class=&quot;mx-3 btn btn-sm d-flex align-items-center btn-view-modal&quot;]</value>
      <webElementGuid>33f2d33e-8fe7-4bde-9830-e12d1dd70d7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='kelulusan-table']/tbody/tr/td[8]/span/div/a</value>
      <webElementGuid>5ab446ea-a86c-48bf-b57f-7d0fe3d5edeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ditolak'])[1]/following::a[1]</value>
      <webElementGuid>35daa001-95d8-4365-956b-a026eec16574</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PN'])[1]/following::a[1]</value>
      <webElementGuid>9afbb349-1e4f-4ecb-82e3-d9cd049b1424</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='spo'])[2]/preceding::a[1]</value>
      <webElementGuid>a24ac21f-1769-4af5-be69-306a1a6d04f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jabatan Khidmat Pengurusan'])[2]/preceding::a[1]</value>
      <webElementGuid>b38566b9-3022-4368-9eec-fa271827e52b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[38]</value>
      <webElementGuid>92ac60be-a423-4a18-a92a-4ad4874e1300</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/a</value>
      <webElementGuid>0c0de32b-4479-44a1-b49f-95b75eeab70e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#']</value>
      <webElementGuid>07e5b72f-25ee-45be-8191-da769c68635e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
