<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Permohonan Saya_kelulusan-tab</name>
   <tag></tag>
   <elementGuidId>b92b9ec8-e86b-4156-8a89-45fdd844dd86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='kelulusan-tab']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#kelulusan-tab</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fcce15e5-5309-4efc-a55a-ebd0df65d918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d03ec9c1-b8c7-4f4b-af61-c567c5e6c248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>kelulusan-tab</value>
      <webElementGuid>8045f3c8-e613-49d8-bda7-c8bd0fab5957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-100 btn btn-sub-button show-tab</value>
      <webElementGuid>ae8cb930-8182-4a70-9967-138c3e8ae228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Kelulusan
        </value>
      <webElementGuid>060db02b-2d78-41d2-8a28-4b8037576e0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kelulusan-tab&quot;)</value>
      <webElementGuid>b20ba9fe-a29c-4cc0-8266-56fa07d30520</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='kelulusan-tab']</value>
      <webElementGuid>79e0799c-8de3-4369-ad6c-bd37d0c99e23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Permohonan Saya'])[1]/following::button[1]</value>
      <webElementGuid>aa857315-4f82-4af2-80bf-8fe790dffc2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Peringatan:'])[1]/following::button[2]</value>
      <webElementGuid>10dddf70-5b23-4efa-a5ab-1a09c12c3e83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Permohonan Saya'])[2]/preceding::button[1]</value>
      <webElementGuid>4485a2e7-bd11-45a1-9a2f-627ef18dc625</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kelulusan']/parent::*</value>
      <webElementGuid>0e9db6b3-ff72-431d-b834-8ed849aad79b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button[2]</value>
      <webElementGuid>6cad6a3e-7837-40bc-bab7-626c5ab97960</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'kelulusan-tab' and (text() = '
            Kelulusan
        ' or . = '
            Kelulusan
        ')]</value>
      <webElementGuid>7b68788a-c931-4bf7-8dcb-2f21c3a3cbb7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
