<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Log Keluar_mobile-collapse</name>
   <tag></tag>
   <elementGuidId>dd84bcd4-779c-4051-adc3-29de1936f07d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mobile-collapse</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='mobile-collapse']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#mobile-collapse</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>67a950aa-fad8-4aee-a2a8-a87cb88e54cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#!</value>
      <webElementGuid>aac4163a-0bcd-4cee-a126-6b0bc3ff0591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dash-head-link</value>
      <webElementGuid>26093874-668b-4bb7-9f5d-e5ab5810120c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mobile-collapse</value>
      <webElementGuid>68222c0f-394c-4d00-8b67-4ebb8b618a4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mobile-collapse&quot;)</value>
      <webElementGuid>580f7926-a1cb-4d35-8f44-22a785e9c760</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='mobile-collapse']</value>
      <webElementGuid>de7de2dd-fa5a-4455-b303-09d1c190ee97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log Keluar'])[1]/following::a[1]</value>
      <webElementGuid>756e8fde-f1a7-4deb-9bd4-77db61c67288</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Post Peletakan'])[1]/following::a[2]</value>
      <webElementGuid>b5c5d9ea-5f9c-4970-bf12-f50279037670</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hi, company!'])[1]/preceding::a[1]</value>
      <webElementGuid>0ce07a18-8efc-4a35-9249-ac757cde19a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profil'])[1]/preceding::a[2]</value>
      <webElementGuid>3e0af63c-9a64-41c9-9462-a1cb7d6f46ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#!')]</value>
      <webElementGuid>eab9132f-7054-4e6e-b74f-3fdea8589502</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/div/div/ul/li/a</value>
      <webElementGuid>976b4200-752b-4b91-8294-8757bb98313d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#!' and @id = 'mobile-collapse']</value>
      <webElementGuid>4d074f08-94f1-4a8e-a248-d5de5a2f5858</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
